/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemavendas.apresentacao;

/**
 *
 * @author helder
 */
public class TelaInicialForm extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialForm
     */
    public TelaInicialForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuVenda = new javax.swing.JMenu();
        itmVendaInserir = new javax.swing.JMenuItem();
        itmVendaConsultar = new javax.swing.JMenuItem();
        mnuProduto = new javax.swing.JMenu();
        mnuCliente = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Vendas");
        setExtendedState(6);

        mnuCadastro.setText("Cadastro");

        mnuVenda.setText("Venda");

        itmVendaInserir.setText("Inserir");
        itmVendaInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVendaInserirActionPerformed(evt);
            }
        });
        mnuVenda.add(itmVendaInserir);

        itmVendaConsultar.setText("Consultar");
        itmVendaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVendaConsultarActionPerformed(evt);
            }
        });
        mnuVenda.add(itmVendaConsultar);

        mnuCadastro.add(mnuVenda);

        mnuProduto.setText("Produto");
        mnuCadastro.add(mnuProduto);

        mnuCliente.setText("Cliente");
        mnuCadastro.add(mnuCliente);

        barraMenu.add(mnuCadastro);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmVendaInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVendaInserirActionPerformed
        CadastroVendaForm cadastroVendaForm = 
                new CadastroVendaForm();
        cadastroVendaForm.setVisible(true);
    }//GEN-LAST:event_itmVendaInserirActionPerformed

    private void itmVendaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVendaConsultarActionPerformed
        ConsultaVendasForm telaConsulta = new ConsultaVendasForm();
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_itmVendaConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itmVendaConsultar;
    private javax.swing.JMenuItem itmVendaInserir;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenu mnuProduto;
    private javax.swing.JMenu mnuVenda;
    // End of variables declaration//GEN-END:variables
}
